package cmd

import (
	"os"

	"github.com/spf13/cobra"
)

type options struct {
	serverURL    string
	clientID     string
	clientSecret string
}

var opts options
var excludeDirs []string

var rootCmd = &cobra.Command{
	Use:   "gridops",
	Short: "Syncs Fogg markers with the Grid API",
	Long: `gridops is a tool to synchronize local marker files (.grid-state.yaml)
generated by Fogg with the remote Grid API.`,
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func envDefault(key, fallback string) string {
	if val := os.Getenv(key); val != "" {
		return val
	}
	return fallback
}

func init() {
	rootCmd.PersistentFlags().StringVar(&opts.serverURL, "server", envDefault("GRID_API_URL", ""), "Grid API base URL (or use GRID_API_URL)")
	rootCmd.PersistentFlags().StringVar(&opts.clientID, "client-id", envDefault("GRID_CLIENT_ID", ""), "Grid service account client ID (or use GRID_CLIENT_ID)")
	rootCmd.PersistentFlags().StringVar(&opts.clientSecret, "client-secret", envDefault("GRID_CLIENT_SECRET", ""), "Grid service account client secret (or use GRID_CLIENT_SECRET)")
	rootCmd.PersistentFlags().StringSliceVar(&excludeDirs, "exclude-dirs", []string{"node_modules", ".terraform", ".git", "dist", "build", "target", ".next", ".turbo"}, "Directory names to exclude from scanning")
}
