# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "global" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444"
    lock_address   = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444/lock"
    unlock_address = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444/unlock"






  }
}
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "vpc" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555"
    lock_address   = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555/lock"
    unlock_address = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555/unlock"






  }
}
locals {
  vpc_vpc_id             = data.terraform_remote_state.vpc.outputs.vpc_id
  vpc_private_subnet_ids = data.terraform_remote_state.vpc.outputs.private_subnet_ids
}
