# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "global" {
  backend = "s3"
  config = {


    bucket = "some-bucket"

    key     = "terraform/proj/global.tfstate"
    region  = "us-west-2"
    profile = "profile"


  }
}
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "vpc" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555"
    lock_address   = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555/lock"
    unlock_address = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555/unlock"






  }
}
